//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.psd2kpiq.dto;

import java.util.ArrayList;
import java.util.List;

public class MovimentiCcResponse
    extends BaseResponse
{

	private static final long serialVersionUID = -1012590495918766968L;
	
	protected List<Movimento> movimento;

    /**
     * Gets the value of the movimento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the movimento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMovimento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Movimento }
     * 
     * 
     */
    public List<Movimento> getMovimento() {
        if (movimento == null) {
            movimento = new ArrayList<Movimento>();
        }
        return this.movimento;
    }

}
