//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package com.ibm.psd2kpiq.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;

public class Movimento implements Serializable {

	private static final long serialVersionUID = 1L;
	
	protected int numeroOrdine;
    protected Integer rigaOrdine;
    protected int dipendenzaOrdine;
    protected Calendar dataOrdine;
    protected int canaleMovimento;
    protected Calendar dataValuta;
    protected String descrizione;
    protected String descrizioneBreve;
    protected BigDecimal importo;
    protected BigDecimal saldoContabileProgressivo;
    protected int tipologia;
    protected int categoriaMovimento;
    protected boolean trasmesso;

    /**
     * Gets the value of the numeroOrdine property.
     * 
     */
    public int getNumeroOrdine() {
        return numeroOrdine;
    }

    /**
     * Sets the value of the numeroOrdine property.
     * 
     */
    public void setNumeroOrdine(int value) {
        this.numeroOrdine = value;
    }

    /**
     * Gets the value of the rigaOrdine property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRigaOrdine() {
        return rigaOrdine;
    }

    /**
     * Sets the value of the rigaOrdine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRigaOrdine(Integer value) {
        this.rigaOrdine = value;
    }

    /**
     * Gets the value of the dipendenzaOrdine property.
     * 
     */
    public int getDipendenzaOrdine() {
        return dipendenzaOrdine;
    }

    /**
     * Sets the value of the dipendenzaOrdine property.
     * 
     */
    public void setDipendenzaOrdine(int value) {
        this.dipendenzaOrdine = value;
    }

    /**
     * Gets the value of the dataOrdine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDataOrdine() {
        return dataOrdine;
    }

    /**
     * Sets the value of the dataOrdine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataOrdine(Calendar value) {
        this.dataOrdine = value;
    }

    /**
     * Gets the value of the canaleMovimento property.
     * 
     */
    public int getCanaleMovimento() {
        return canaleMovimento;
    }

    /**
     * Sets the value of the canaleMovimento property.
     * 
     */
    public void setCanaleMovimento(int value) {
        this.canaleMovimento = value;
    }

    /**
     * Gets the value of the dataValuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDataValuta() {
        return dataValuta;
    }

    /**
     * Sets the value of the dataValuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataValuta(Calendar value) {
        this.dataValuta = value;
    }

    /**
     * Gets the value of the descrizione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * Sets the value of the descrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizione(String value) {
        this.descrizione = value;
    }

    /**
     * Gets the value of the descrizioneBreve property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizioneBreve() {
        return descrizioneBreve;
    }

    /**
     * Sets the value of the descrizioneBreve property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizioneBreve(String value) {
        this.descrizioneBreve = value;
    }

    /**
     * Gets the value of the importo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImporto() {
        return importo;
    }

    /**
     * Sets the value of the importo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporto(BigDecimal value) {
        this.importo = value;
    }

    /**
     * Gets the value of the saldoContabileProgressivo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSaldoContabileProgressivo() {
        return saldoContabileProgressivo;
    }

    /**
     * Sets the value of the saldoContabileProgressivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSaldoContabileProgressivo(BigDecimal value) {
        this.saldoContabileProgressivo = value;
    }

    /**
     * Gets the value of the tipologia property.
     * 
     */
    public int getTipologia() {
        return tipologia;
    }

    /**
     * Sets the value of the tipologia property.
     * 
     */
    public void setTipologia(int value) {
        this.tipologia = value;
    }

    /**
     * Gets the value of the categoriaMovimento property.
     * 
     */
    public int getCategoriaMovimento() {
        return categoriaMovimento;
    }

    /**
     * Sets the value of the categoriaMovimento property.
     * 
     */
    public void setCategoriaMovimento(int value) {
        this.categoriaMovimento = value;
    }

    /**
     * Gets the value of the trasmesso property.
     * 
     */
    public boolean isTrasmesso() {
        return trasmesso;
    }

    /**
     * Sets the value of the trasmesso property.
     * 
     */
    public void setTrasmesso(boolean value) {
        this.trasmesso = value;
    }

}
