//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4)
//


package com.ibm.psd2kpiq.dto;

import java.util.Calendar;

public class MovimentiCcRequest
    extends BaseRequest
{

	private static final long serialVersionUID = 1L;
	
    protected Calendar dataA;
    protected Calendar dataDa;
    protected int numeroMovimenti;
    protected int canaleMovimento;
    protected int tipologia;
    protected int categoriaMovimento;


    /**
     * Gets the value of the dataA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDataA() {
        return dataA;
    }

    /**
     * Sets the value of the dataA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataA(Calendar value) {
        this.dataA = value;
    }

    /**
     * Gets the value of the dataDa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDataDa() {
        return dataDa;
    }

    /**
     * Sets the value of the dataDa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataDa(Calendar value) {
        this.dataDa = value;
    }

    /**
     * Gets the value of the numeroMovimenti property.
     * 
     */
    public int getNumeroMovimenti() {
        return numeroMovimenti;
    }

    /**
     * Sets the value of the numeroMovimenti property.
     * 
     */
    public void setNumeroMovimenti(int value) {
        this.numeroMovimenti = value;
    }

    /**
     * Gets the value of the canaleMovimento property.
     * 
     */
    public int getCanaleMovimento() {
        return canaleMovimento;
    }

    /**
     * Sets the value of the canaleMovimento property.
     * 
     */
    public void setCanaleMovimento(int value) {
        this.canaleMovimento = value;
    }

    /**
     * Gets the value of the tipologia property.
     * 
     */
    public int getTipologia() {
        return tipologia;
    }

    /**
     * Sets the value of the tipologia property.
     * 
     */
    public void setTipologia(int value) {
        this.tipologia = value;
    }

    /**
     * Gets the value of the categoriaMovimento property.
     * 
     */
    public int getCategoriaMovimento() {
        return categoriaMovimento;
    }

    /**
     * Sets the value of the categoriaMovimento property.
     * 
     */
    public void setCategoriaMovimento(int value) {
        this.categoriaMovimento = value;
    }

}
